config/routes.rb
TrackerApp::Application.routes.draw do
  devise_for :users do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_up", :to => "devise/registrations#new"
  end

  namespace :api do
    namespace :v1 do
      resources :locations do
        get 'friends', :on => :collection
      end
    end
  end

    root :to => "home#index"

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => 'User'

  before_create :set_approved_to_false

  def set_approved_to_false
    write_attribute(:approved, 'f')
  end

  def approve!
    update_attribute(:approved, 't')
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates_presence_of :longtitude, :latitude

  belongs_to :user
end

app/models/location_request.rb
class LocationRequest < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :first_name, :last_name

  has_many :friendships
  has_many :locations

  has_many :pending_friends, :through => :friendships, :source => :friend,
    :conditions => ['friendships.approved = ?', false]

  has_many :friends, :through => :friendships,
    :conditions => ['friendships.approved = ?', true]

  has_many :inverse_friendships, :class_name => 'Friendship', :foreign_key => 'friend_id'

  has_many :inverse_friends, :through => :inverse_friendships, :source => :user,
    :conditions => ['friendships.approved = ?', true]

  has_many :friend_requests, :through => :inverse_friendships, :source => :user,
    :conditions => ['friendships.approved = ?', false]

  has_many :friendship_requests, :class_name => 'Friendship', :foreign_key => 'friend_id',
    :conditions => ['friendships.approved = ?', false]

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :remember_me, :name

  before_save :generate_api_key

  def add_friend_and_approve!(friend)
    friends << friend
    friendship_request = friend.friendship_requests.last

    raise "Friendship request is nil, could not approve!" if friendship_request.nil?

    friendship_request.approve!
  end

  def self.friends_locations(user)
    scope = Location.select('locations.*, u.id, u.first_name, u.last_name, u.apikey')
    scope = scope.joins('inner join users u on u.id = locations.user_id')
    scope = scope.joins('inner join friendships on friendships.friend_id = u.id or friendships.user_id = u.id')
    scope = scope.where('friendships.user_id = ? or friendships.friend_id = ?', user.id, user.id)
    scope = scope.where('friendships.approved = ? and locations.user_id != ?', true, user.id)
    scope = scope.order('locations.created_at DESC')
    scope = scope.group('u.id')
  end

  def generate_api_key
    if self.email_changed?
      self[:apikey] = Digest::MD5.hexdigest(self[:email].downcase)
    end
  end

  def name=(first_and_last_names)
    parts = first_and_last_names.split(/\s+/)

    if parts && parts.length > 1
      self[:first_name] = parts[0]
      self[:last_name] = parts[1..-1].join(' ')
    end
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
end

app/controllers/api/v1/friends_controller.rb
class Api::V1::FriendsController < Api::BaseController
end

app/controllers/api/v1/locations_controller.rb
class Api::V1::LocationsController < Api::BaseController
  before_filter :authenticate_with_api_key

  def create
    @location = @user.locations.build(params[:location])

    respond_to do |format|
      if @location.save
        format.json { render :json => @location, :status => :ok }
      else
        format.json { render :json => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  def friends
    @locations = User.friends_locations(@user)

    respond_to do |format|
      format.json { render :json => @locations, :status => :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authenticate_with_api_key
    api_key = params[:apikey]
    @user = User.find_by_apikey(api_key)

    unless @user
      render :json => {}, :status => :unauthorized
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
      
      if @user.save
        redirect_to root_path, :notice => "User was successfully created."
      else
        render :action => "new"
      end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to root_path, :notice => "User details were successfully updated."
    else
      render :action => "edit"
    end
  end
end

app/helpers/api/base_helper.rb
module Api::BaseHelper
end

app/helpers/api/v1/friends_helper.rb
module Api::V1::FriendsHelper
end

app/helpers/api/v1/locations_helper.rb
module Api::V1::LocationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'googlemap.js' %>
<% end %>

<div id="main-area" style="width: 650px; height: 600px;">
  <div style="width: 650px; height: 600px;" id="googlemap" data-apikey="<%= current_user.apikey %>"></div>
</div>
<div id="friends-area">	
	<div class="friend">
		<a href="#"><img src="images/online.png" class="status" /></a> <p>online friend</p>
	</div>
	<div class="friend">
		<a href="#"><img src="images/offline.png" class="status" /></a><p>offline friend</p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>TrackerApp</title>
  <%= stylesheet_link_tag :all %>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <%= javascript_include_tag 'application.js' %>
  <%= yield :javascripts %>
  <%= csrf_meta_tag %>
</head>
<body <%= yield :body_tag %>>
	<div class="search-area">
		<form action="login.html" method="post">
			<img src="/images/logo_50.png" alt="TrackApp" />
			<p class="left">Android TrackApp <span class="grey"> Track or be tracked, but do it with TrackerApp</span> </p> 
			<p class="right"><input type="text" class="grey" value="Search"></input></p>
		</form>
	</div>		
	<div id="wrapper">
		<div id="header">
			<div class="logo-area">
				<img src="/images/logo.png" alt="logo" />
				<p class="quote"> "Track or be tracked, but do it with TrackerApp." </p>
			</div>			
			<div class="login-area">  
				<% if user_signed_in? %> 
				

<ul class="nav">
	<li>Signed in as <a href="#" class="user"><%= current_user.first_name + " " + current_user.last_name %></a>
		<ul>
			<li><%= link_to "Edit profile", edit_user_registration_path(@user) %></li>
			<li><%= link_to "Sign out", destroy_user_session_path %></li>
		</ul>
	</li>
</ul>
				
				
					
					
				<%= image_tag avatar_url(current_user) %>
				<% end %>  
			</div>  
			
		</div>
		<div id="content">
			<%=yield %> 	
		</div>	
	</div>
</body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name), :class => 'spacing' %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), :class => 'spacing' %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>